version: '3.7'
services:
  metabase_db:
    container_name: metabase_db
    image: 'postgres:13'
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: application_data
    ports:
      - '4532:5432'
    volumes:
      - './metabase_db-data:/var/lib/postgresql/data'
  metabase_app:
    image: 'metabase/metabase:v0.36.6'
    container_name: metabase_app
    mem_limit: 5000m
    restart: unless-stopped
    environment:
      JAVA_TOOL_OPTIONS: '-Xmx4g'
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: application_data
      MB_DB_PORT: 5432
      MB_DB_USER: user
      MB_DB_PASS: password
      MB_DB_HOST: metabase_db
      MB_DB_CONNECTION_URI: 'postgres://metabase_db:5432/application_data?user=user&password=password'
    ports:
      - '3000:3000'
    depends_on:
      - metabase_db
    links:
      - metabase_db
volumes:
  metabase_db-data: null